### ISSUE TITLE
Progress Check 1 Feedback

### ISSUE THREAD

**Issue by brandonbrown** [fullsail/capstone-TracySpitler#16]
> Concerns updates to #1 

You've handled this Holiday week well. You've delivered on nearly every aspect of the sprint and have built a good momentum to work from. You have also been involved and active on Discord with both instructors and classmates which has been extremely helpful. You were challenged to update your concept to better integrate an API and came up with some great ideas, but they seem to be missing from your current documentation.

**General Notes**
- **User Stories**
  - Your User Stories are formatted extremely well. They and the functional requirements attached to each are exactly as we expected. Well done. Feedback on the context of user stories will be coming in another update.
- **Concept Prototype**
  - This seems to be missing the discussed concept pivots from Discord. To help clarify this, can you give a short screen by screen description of what the user is hoping to achieve with each screen?
- **Project Pitch**
  - Not updated: https://github.com/fullsail/capstone-TracySpitler/tree/concepts/docs

**Action Items**
* [x] Update `/docs/readme.md` 
* [x] Clarify intentions and decisions of the **Concept Prototype**

**Follow up**
Please discuss with myself on Discord any concerns or things that may be holding you back from delivering on the Action Items listed above.

> Close this issue after **all** action items and follow up has been completed.

**Team Members Involved**

| Member        | Username           | 
| ------------- |:-------------:| 
| Brandon | @brandonbrown |

**Comment by TracySpitler** [comment]
All action items have been completed.
