### ISSUE TITLE
Sprint 3 Release Notes

### ISSUE THREAD

**Issue by reactivepixel** [FullSail/capstone-TracySpitler#60]
**General Notes**
* We are not sure which pull request we should be evaluating. Releases should be individual pull requests from release to master, for each sprint.
* New functional requirements have been added but not assigned to a milestone.
* Logical Error: If you have no lists in the database the `next()` in the lists middleware is never executed.
* Mongo not referenced in docs as required

**Action Items**
* [x] Assign all userstory/func req issues to a related milestone.
* [x] Remove `node_modules` from repo (research removing cached folders from git)
* [x] Add npm start script
* [ ] Fix list middleware
* [x] Add mongo to docs

## Summary
No idea what is actually being released due to issues not being linked or referenced in a valid pull request.

Pull request rejected, please resolve the items noted above and notify the capstone team for a second evaluation.

**Follow up**
Follow up in this thread, tagging @reactivepixel and @brandonbrown and please explain the status of your released sprints. We just need this clarified as there seems to be a slight irregularity. 

> Close this issue after **all** action items and follow up has been completed.

**Team Members Involved**

| Member        | Username           | 
| ------------- |:-------------:| 
| Chapman | @reactivepixel |
| Brandon | @brandonbrown |

**Comment by TracySpitler** [comment]
_from Discord_

__Tracy:__
I'm so sorry about the GitHub mishap. I had merged Sprint 3 with Release before Sprint 2 was merged with Master, so when I merged Sprint 2, Sprint 3 went with it. What's the best way to undo something like this? I don't want to mess anything up. Should I revert the Sprint 2 release and then revert the Sprint 3 changes, then make the separate pull requests? Do you have any suggestions?

__Chapman:__
just add that explanation to the feedback issue for when we look back upon it later and tackle the other items. Pulling it out would be a painful experience with little benefit :smile:
